apiVersion: v1
kind: Namespace
metadata:
  name: devops-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nexus-deployment"
  namespace: devops-ns
  labels:
    app: "nexus"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: "nexus"
  template:
    metadata:
      labels:
        app: "nexus"
    spec:
      containers:
        - image: sonatype/nexus3:3.38.0
          env:
          - name: MAX_HEAP
            value: "1000m"
          - name: MIN_HEAP
            value: "400m"
          imagePullPolicy: Always
          name: "nexus"
          ports:
          - containerPort: 8081
            name: "nexus"
          volumeMounts:
          - name: nexus-data
            mountPath: /nexus-data
          - name: tz-istanbul
            mountPath: /etc/localtime
      volumes:
      - name: nexus-data
        hostPath:
          path: /nexus-data
      - name: tz-istanbul
        hostPath:
          path: /usr/share/zoneinfo/Europe/Istanbul
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  namespace: devops-ns
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
  - name: "8081"
    targetPort: 8081
    port: 8081
    nodePort: 32000